#!/bin/bash
set -e

PLUGIN_NAME="kassisol/gitvol"
IMAGE_NAME="gitrootfs"
ROOTFS_DIR="rootfs"

DIST_PLUGIN_FILE="dist/plugin"

source $(dirname $0)/version

echo "build-plugin: Building ${IMAGE_NAME}:${VERSION}"

cd $(dirname $0)/plugin

if [ -x "prebuild.sh" ]; then
	./prebuild.sh
fi

docker image build -t ${IMAGE_NAME} .

if [ -d "build" ]; then
	rm -rf build
fi

cd ../../

id=$(docker create ${IMAGE_NAME} true)

if [ -d "${ROOTFS_DIR}" ]; then
	rm -rf ${ROOTFS_DIR}
fi
mkdir -p ${ROOTFS_DIR}

docker export "${id}" | tar -x -C ${ROOTFS_DIR}
docker container rm -vf "${id}"

docker image rm ${IMAGE_NAME}

cd ..

if [ `docker plugin ls | awk -v plugin="${PLUGIN_NAME}:${VERSION}" '{if($2 == plugin) print $0 }' | wc -l` -eq 1 ]; then
	docker plugin rm ${PLUGIN_NAME}:${VERSION}
fi

docker plugin create ${PLUGIN_NAME}:${VERSION} docker-volume-git/
if [ $? -eq 0 ]; then
	echo "${PLUGIN_NAME}:${VERSION}" > docker-volume-git/${DIST_PLUGIN_FILE}
fi

echo "build-plugin: DONE"
